name: Deploy GitHub Pages

# once pushed to master branch
on:
  push:
    branches:
      - master

# jobs to build and deploy
jobs:
  build-and-deploy:
    # server env: latest Ubuntu
    runs-on: ubuntu-latest
    steps:
      # pull project
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      # build project
      - name: Build
        run: echo $VSSUEID
        env:
          VSSUEID: ${{ secrets.VSSUEID }}
          VSSUESECRET: ${{ secrets.vssuesecret }}
        run: echo $VSSUEID
        run: npm install && npm run docs:build

      # deploy to Github Pages
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BRANCH: gh-pages
          FOLDER: docs/.vuepress/dist
